### ISSUE TITLE
Enabler: Setup Scaffolding

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform-dynamic-services#1]
# Title of Enabler

Create web application project and support around it.

Optionally we turn off things in the current Cancer.gov Web Config.

> From Scratch -- 3-4 days *Minimum* at start
   * This makes the code easier to understand, but we have lots of dependencies in our modules, so it is not easy to *just* copy something in. That may require more things and more things, untill we end up where we started.
   * Probably should have a spike

> Clear out current solution -- 3-4 days *maximum* at the end (as defined by all appmodules and content moving to Drupal)
   * This turns off the old code, but you are left with a LOT of old inert code and no understanding of where it is used.

> **ESTIMATE** NN

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* References: *URL to web site with examples*
* Web Page: *Here goes a URL to an existing web page*

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Sub-Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction

**Comment by blairlearn** [comment]
overtaken by events
