### ISSUE TITLE
Story: Clinical Trials Redirect

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform-dynamic-services#2]
## As a [role], I want [feature], so that [benefit]

`<add name="NCTIDRedirectModule" type="CancerGov.ClinicalTrials.Basic.v2.NCTIDRedirectModule, CancerGov.BasicCTSv2" />`

> **ESTIMATE**  1-2 days testing / move. 
    * This is the easiest to ensure is working, but if we are making a new service this has a LOT of dependencies...

### Acceptance Criteria

```gherkin
Scenario: [title]
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- More notes, or technical nuances/direction

**Comment by blairl-nih** [comment]
* Remove handling for legacy `/about-cancer/treatment/clinical-trials/search/view` paths.
* Move URL for detail view to the web.config `appSettings` section.

These two changes remove the dependency on the `/publishedContent` directory as well as the dependency on the snippetTemplate code which was used for parsing the clinical trial configuration.
