### ISSUE TITLE
Story: Glossary Link Href Handler

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform-dynamic-services#3]
## As a [role], I want [feature], so that [benefit]

Create a handler for popdefinition.aspx.

* New Handler
* Takes in ID, (and lang, and dictionary and audience) goes off to API and finds correct term and then:
    * If the term exists in a dictionary we have on the site, we 301 redirect there.
      * Dictionary of Cancer Terms English - `Cancer.gov`, `en`, `Patient`
      * Dictionary of Cancer Terms Spanish - `Cancer.gov`, `es`, `Patient`
      * Dictionary of Genetics Terms - `genetics`, `en`, `HealthProfessional`
    * if the term does not , we just spit out the HTML (looking like the old popup) -- this really should be just for search engines.  Does this need images, are their items from a dictionary we don't have that is here... (how much do we need to handle images, videos and related pages)
    * this needs nvcg.css.

> **ESTIMATE** 1 week.

### Acceptance Criteria

```gherkin
Scenario: [title]
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- More notes, or technical nuances/direction

**Comment by blairlearn** [comment]
Completed in d14513f8d065a81a04a7340fc12174b5fd85700d
