### ISSUE TITLE
Story: CTS Print Service

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform-dynamic-services#4]
## As a [role], I want [feature], so that [benefit]

This should stay as is.

The code comes from the following Handlers
```
      <add name="CTSNewPrintRequestHandler" path="CTS.Print/GenCache" verb="POST" type="CancerGov.ClinicalTrials.Basic.v2.HttpHandlers.CTSCachedPrintRequestHandler,CancerGov.BasicCTSv2" />
      <add name="CTSCachedPrintRequestHandler" path="CTS.Print/Display" verb="GET" type="CancerGov.ClinicalTrials.Basic.v2.HttpHandlers.CTSCachedPrintRequestHandler,CancerGov.BasicCTSv2" />
```

This carries with it connectionStrings. Which means that we need to deal with configs. This should not break the single web.config, because we should use a config source for the connection strings section.

This is in the same assembly as the redirect, so if there should be no other overhead. 

> **ESTIMATE** 1-2 days given that it is as-is,

### Acceptance Criteria

```gherkin
Scenario: [title]
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- More notes, or technical nuances/direction

**Comment by blairlearn** [comment]
This was implemented in https://github.com/NCIOCPL/clinical-trials-search-print
